### PR TITLE
Added AnimationFlag

### PR DESCRIPTION
**Pull request by Tanjitsu**
Added AnimationFlag 49 SecondayUpper body animations only.

This is used for Handcuffed animations while walking ect.
I would imagine there are more which are missing but I was specifically using this one.

### CODE REVIEW

**Comment by kagikn** [comment]
Actually, we've already added all the flags used in `ANIMATION_FLAGS` in `commands_task.sch` and `eScriptedAnimFlags` bitset in `AnimTaskFlags.psc`. `ANIMATION_FLAGS` in `commands_task.sch` doesn't define a combined value for 49, so I'm not adding an enum member for 49. [What `eScriptedAnimFlags` defines](https://alexguirre.github.io/rage-parser-dumps/dump.html?game=gta5&build=3028&search=eScriptedAnimFlags#eScriptedAnimFlags) can be checked in the production exe by searching for the name values hashed by joaat (with no character conversions).

Also, what you tried to add would loop the animation despite what name explains... not as important as what `ANIMATION_FLAGS` and `eScriptedAnimFlags` defines though.

**Comment by Tanjitsu** [comment]
Ped felon;
felon.Task.PlayAnimation("mp_arresting", "idle", 8, -8, -1, AnimationFlags, 0);
Script.Wait(6000);
felon.Task.GoTo(Game.Player.Character.Position);

Just a random example, not directly tested the above code but...

"mp_arresting", "idle" plays and the felon stands with hands behind back for the "Script.Wait" period.
When Task.GoTo fires, the animation resets and the felon walks normally to the car.

I tested the provided animation flags and could not get the felon to remain with hands behind his back while walking.
I added no. 49 and it started working fine.

**Comment by kagikn** [comment]
You can use the bitwise OR operator to combine enum flags.

A source code leak incident reveals how most bit set flags are intended to use in the game too, without having to disassemble the exe (which may require to do extensively). After that happened, I'm not adding combined flags of **known** bit set flags that aren't defined in the enum definitions in the source code. I'm willing to add combined flags that are defined in the enum definitions in the source code because we could excuse like "even Rockstar used this combined flag!" without discussing how much such combined flags are useful, while how much useful custom defined ones is subjective when we know every non-combined flag in a enum.

**Comment by Tanjitsu** [comment]
Ah, it has been a while since I worked with this, combined 32 + 16 + 1 provided the correct effect.
Thank you for clarifying the functionality.

**Pull request closed without merging**
