### PR TITLE
docs: correct grammar fixes in README.md

### PR DESCRIPTION
**Pull request by Michael21107**
minor grammar fixes and change of the SHV link to a non-broken site

### CODE REVIEW

**Comment by kagikn** [comment]
Thank you! SHV link wasn't broken though.

**Comment by Michael21107** [comment]
no problem, it wasnt broken but the secure version of the site (`https`, which i believe was linked atm of me writing the commit) looks broken to me

**Comment by kagikn** [comment]
dev-c.com has problems on the https protocol, not our problems. That's shit since you can't verify if responses came via http is malformed in a firm way, especially if some of the content of website is updated.

**Comment by Michael21107** [comment]
I know it's his problem, i just changed it so that people see the nicer site

**Comment by kagikn** [comment]
you know, this PR changes how you see a string for the SHV page but doesn't change the actual link to the SHV page (doesn't even change the protocol to use). Maybe your browser implicitly redirected, but at least the commit made by merging this PR doesn't have any changes on the actual link to the SHV page.

**Comment by Michael21107** [comment]
i see, thanks

**Pull request merged**
