### PR TITLE
Introduce GitHub Actions

### PR DESCRIPTION
**Pull request by kagikn**
No publishing job on NuGet or consideration for new tags yet, but at least we can build the solution with the new workflow. We can reserve `System.Runtime.CompilerServices.IsConst` for `GTA.UI.WIDTH` and `GTA.UI.HEIGHT` of v2 API too.
We should be careful with the publishing job, so I create a pull request. 

Mentioned in [a comment](https://github.com/crosire/scripthookvdotnet/issues/1222#issuecomment-1546849919) in #1222 btw.

### CODE REVIEW

**Comment by justalemon** [comment]
On LemonUI, I do something complicated yet clean.

I have one job that Lints and Builds, and another jobs that Deploys. On the Build step, I post the Debug and Release artifacts:

```yml
  lint-and-compile:
    strategy:
      matrix:
        configuration: [Debug, Release]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v2.1.0
        with:
          dotnet-version: "7.0.x"
      - run: dotnet restore ${{ github.event.repository.name }}.sln
      - uses: justalemon/VersionPatcher@v0.5.1
        with:
          version: 1.9.3.${{ github.run_number }}
          use-tag: true
          csproj-files: "**/root.props"
      - run: dotnet build ${{ github.event.repository.name }}.sln -c ${{ matrix.configuration }}
        working-directory: ${{ env.GITHUB_WORKSPACE }}
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.repository.name }}.${{ matrix.configuration }}
          path: bin/${{ matrix.configuration }}
```

Then I have another job that does the actual deployment, but only on releases:

```yml
  deploy:
    runs-on: ubuntu-22.04
    if: ${{ github.event_name == 'release' }}
    needs:
      - lint-and-compile
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v2.1.0
        with:
          dotnet-version: "7.0.x"
      - uses: actions/download-artifact@v3
        with:
          name: ${{ github.event.repository.name }}.Release
          path: bin/Release
      - run: ls -R
        working-directory: bin/Release
      - run: 7z a ${{ github.event.repository.name }}.zip ${{ github.workspace }}/bin/Release/*
      - run: dotnet nuget push "**/*.nupkg" -s 'https://api.nuget.org/v3/index.json' -k ${{secrets.NUGET}}
      - uses: ncipollo/release-action@v1.10.0
        with:
          allowUpdates: true
          artifactErrorsFailBuild: true
          artifacts: ${{ github.event.repository.name }}.zip
          omitBodyDuringUpdate: true
          omitDraftDuringUpdate: true
          omitNameDuringUpdate: true
          omitPrereleaseDuringUpdate: true
```

**Comment by kagikn** [comment]
I'm waiting for crosire's clear decision about my admin role for this project/repo. Looks like you don't necessarily need an admin role to create a release via GitHub API and you can do this with a write access, but I think I need to grab an admin role before I can configure API tokens for NuGet packages without exposure.

**Comment by justalemon** [comment]
No need for that. You can enable certain permissions on the worker. Check https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs

**Comment by kagikn** [comment]
So I can create releases via external actions with certain permissions. And now [crosire gave me an admin role for the organization](https://github.com/scripthookvdotnet/scripthookvdotnet/issues/1222#issuecomment-1572592866) and I configured a NuGet API key so I can publish API packages without the key getting exposed.

I'm planning to release the new version of SHVDN after SHV gets updated for the new GTA version since [an new update of GTA was announced](https://www.rockstargames.com/newswire/article/75k42a284a7a43/gta-online-san-andreas-mercenaries-coming-june-13) and we would add new hashes again. I should get this done before that time comes...

**Comment by kagikn** [comment]
I think this PR got as sophiscated for the status check as the previous AppVeyor workflow. Removed the files for AppVeyor CI to prevent unintended accidents.
I put my personal token for the GitHub release API since I'm not a fan of the github-actions bot as a release author (if you use `github.token` for the release API, then you will see). I haven't seen any repos that have any releases with the github-actions bot author except for Vue.js, either. I've looked into React, Node.js, Ruby on Rails, Laravel, MAME (emulator), and DeSmuME for their releases on GitHub.

When we add a job or workflow where API packages will be automatically published to NuGet, we would use `msbuild [project filename] -t:pack /p:Configuration=Release /p:Platform="x64"` because you can't use the `nuget` command (no support for SDK-style projects) or `dotnet pack` (no support for projects that depends on MSVC projects) for the SHVDN solution.

**Pull request merged**
