### PR TITLE
docs: Update instructions in README.md

### PR DESCRIPTION
**Pull request by Michael21107**

### CODE REVIEW

**Comment by kagikn** [comment]
I thought deleting "and `ScriptHookVDotNet.ini.example.txt`" would be enough, since the instruction says "Extract all the files **in the root folder**"?

**Comment by Michael21107** [comment]
do you think that people won't by mistake consider folders as files?

**Comment by kagikn** [comment]
ah, I don't expect people to consider the 2 folders as files wrong, but it would be better to explicitly state that you don't need to place the 2 folder to the game folder.

**Comment by Michael21107** [comment]
im going off lspdfr support servers lmao u wont believe the stupidity there until u see it for yourself

**Comment by susegg** [comment]
> ah, I don't expect people to consider the 2 folders as files wrong, but it would be better to explicitly state that you don't need to place the 2 folder to the game folder.

I'd like to introduce myself as someone who thought there was a typo in the [README.md](https://github.com/scripthookvdotnet/scripthookvdotnet/blob/main/README.md) 😂 but only because my stupidity thought you both meant the stable version ....and I spent 10 mins looking for the "2 folders"

_Instruction is fine_

**Comment by Michael21107** [comment]
> > ah, I don't expect people to consider the 2 folders as files wrong, but it would be better to explicitly state that you don't need to place the 2 folder to the game folder.
> 
> I'd like to introduce myself as someone who thought there was a typo in the [README.md](https://github.com/scripthookvdotnet/scripthookvdotnet/blob/main/README.md) 😂 but only because my stupidity thought you both meant the stable version ....and I spent 10 mins looking for the "2 folders"
> 
> _Instruction is fine_

don't worry,people (like me) have done worse😂

**Pull request merged**
